### ISSUE TITLE
How to get 'cunxn' package?

### ISSUE THREAD

**Issue by wangg12** [qassemoquab/nxnrock#1]
Hi Oquab! I am trying to reproduce the weak supervised CNN which is discribed in your CVPR15's paper. I found require 'cunxn' in your  lua scripts, but I can't find where and how to install this package. Could you please help me?

**Comment by qassemoquab** [comment]
Unfortunately, cunxn is only available in that old fork of torch that is provided with the rest of the scripts. 
If you follow the instructions provided, it should work.

**Comment by TalhaMetu** [comment]
Can you please write how to install it? I am newbee :(
